openapi: 3.0.3
info:
  title: Especificación de API bancaria para operaciones de cuentas
  description: |-
    Una API bancaria sencilla que permite dos operaciones:
    - obtener el saldo de la cuenta dado el número de cuenta
    - monto del depósito a una cuenta
  version: 1.0-SNAPSHOT
servers:
- url: http://localhost:8080/api/v1
tags:
- name: cuentas
  description: Operaciones entre cuentas bancarias
paths:
  /cuenta:
    get:
      tags:
      - cuentas
      summary: Obtener información del saldo
      description: Obtener información del saldo usando el número de cuenta
      operationId: getAccount
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cuenta'
        404:
          description: Cuenta no encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CuentaNoEncontradaError'
  /cuenta/deposito:
    post:
      tags:
      - cuentas
      summary: Depositar una cantidad a la cuenta
      description: Inicia una operación de depósito de un monto deseado en la cuenta especificada
      operationId: depositToAccount
      requestBody:
        description: Número de cuenta y monto deseado a depositar
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SolicitudDeposito'
        required: true
      responses:
        204:
          description: Success
        404:
          description: Cuenta no encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CuentaNoEncontradaError'
components:
  schemas:
    Cuenta:
      type: object
      properties:
        balance:
          type: number
    CuentaNoEncontradaError:
      type: object
      properties:
        mensaje:
          type: string
    SolicitudDeposito:
      type: object
      properties:
        numeroCuenta:
          type: string
        cantidadDeposito:
          type: number
